version: '3.8'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password
    volumes:
      - mysql_data:/var/lib/mysql

  custom_apache:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - mysql
    volumes:
      - apache_data:/var/www/html
      - tools:/usr/local/bin
      - htop_config:/root

volumes:
  apache_data:
  mysql_data:
  tools:
  htop_config:
